### ISSUE TITLE
bounds and optimal variables

### ISSUE THREAD

**Issue by edljk** [JuliaOpt/SumOfSquares.jl#111]
I am trying to use SumOfSquares.jl for polynomial optimization.  Adapting Goldstein-Price example, I considered the naive example:

```julia
using SumOfSquares, DynamicPolynomials, MosekTools

@polyvar x y
model = SOSModel(with_optimizer(Mosek.Optimizer))
@variable(model, γ)

f = x^2 + y^2 + 3
@constraint(model, f >= γ)
@objective(model, Max, γ)

optimize!(model)
println(objective_value(model))
```
My questions:
1. Is it possible to add bound constraint on variables like```x >= 2``` in this framework ?
2. How can I get one optimal point `(x,y)`?

Thanks!

**Comment by blegat** [comment]
Yes and yes, you can find an indepth explanation in [this notebook](https://github.com/JuliaOpt/SumOfSquares.jl/blob/master/examples/Polynomial_Optimization.ipynb).
The short answer is:
1. Do `using SemialgebraicSets; S = @set x >= 2` and then do `cref = @constraint(model, f >= γ, domain = S`.
2. Yes, you might be able to get it from `moment_matrix(cref)` using `extractatoms` of [MultivariateMoments](https://github.com/JuliaAlgebra/MultivariateMoments.jl). If you don't get it, you need to increase `maxdegree` in the `@constraint` macro.

**Comment by edljk** [comment]
Thanks a lot!

**Comment by edljk** [comment]
Here is an example of extraction of optimal values without success..: I get (0, 0, 0, 0, 0) which corresponds to a cost value of 78.3392339877376 which is not optimal regarding for instance the output of Mosek..


```julia
using SumOfSquares, DynamicPolynomials, MosekTools, MultivariateMoments

@polyvar x1 x2 x3 x4 x5

P = 3.815442304233332e-9*x1^4 + 1.1350762077340954e-8*x1^3*x4 + 1.2924656406621723e-8*
    x1^2*x2^2 + 1.2924656406621713e-8*x1^2*x3^2 + 1.8423535045292308e-8*x1^2*x4^2 +
    1.0122396387470613e-8*x1^2*x5^2 + 1.9626546799251066e-8*x1*x2^2*x4 + 
    1.962654679925104e-8*x1*x3^2*x4 + 1.1679063042349957e-8*x1*x4^3 + 
    9.520727985261067e-9*x1*x4*x5^2 + 2.7082391734789632e-9*x2^4 + 5.416478346957923e-9*
    x2^2*x3^2 + 1.0942986274762936e-8*x2^2*x4^2 + 6.0187968500882955e-9*x2^2*x5^2 +
    2.70823917347896e-9*x3^4 + 1.0942986274762923e-8*x3^2*x4^2 + 
    6.0187968500882955e-9*x3^2*x5^2 + 3.803191965006821e-9*x4^4 + 5.89938143719703e-9*
    x4^2*x5^2 + 2.351191558377895e-9*x5^4 - 2.4671615505052975e-7*x1^3 - 6.067420144239354e-7*
    x1^2*x4 - 4.6157161458128917e-7*x1*x2^2 - 4.6157161458128896e-7*x1*x3^2 -
    5.796195761865924e-7*x1*x4^2 - 2.618295618996514e-7*x1*x5^2 - 3.9200909602979044e-7*
    x2^2*x4 - 3.9200909602979034e-7*x3^2*x4 - 1.7884878888886506e-7*x4^3 - 
    1.2117276058897292e-7*x4*x5^2 - 0.0008613040832100756*x1^2 - 0.0008973642878906614*x1*
    x4 - 0.0007018298300695713*x2^2 - 0.000701829830069571*x3^2 - 0.0007851143936024227*
    x4^2 - 0.000622769718234522*x5^2 + 0.025271281688104018*x1 + 0.020194288018707807*
    x4 + 78.3392339877376

model = SOSModel(with_optimizer(Mosek.Optimizer))
# create a JuMP decision variable for the lower bound
@variable(model, γ)
# constraints f(x) - γ to be sum of squares
cref = @constraint(model, P >= γ, maxdegree = 10)
# objective 
@objective(model, Max, γ)
# optimize
optimize!(model)    
println(objective_value(model))
# get optimal points
M = moment_matrix(cref)
extractatoms(M, 1e-5)

...
28  5.0e-17  8.0e-15  2.5e-17  7.96e-01   4.547790152e+01   4.543044037e+01   1.4e-18  0.05  
29  4.7e-17  8.0e-15  9.4e-18  9.01e-01   4.494647092e+01   4.493828374e+01   2.2e-19  0.05  
30  4.7e-17  9.4e-14  3.7e-18  9.80e-01   4.493484872e+01   4.493358174e+01   3.4e-20  0.05  
31  4.7e-17  9.4e-14  3.7e-18  1.26e+00   4.493484872e+01   4.493358174e+01   3.4e-20  0.06  
Optimizer terminated. Time: 0.06    

44.93484872223572
Algebraic Set defined by 5 equalities
 -x5 == 0
 -x4 == 0
 -x3 == 0
 -x2 == 0
 -x1 == 0

```

**Comment by blegat** [comment]
`extractatoms` may return an atomic measure which is different from the measure you give it.
At the end, you can see that it is trying to find weights such that the atoms found have the same moments:
https://github.com/JuliaAlgebra/MultivariateMoments.jl/blob/705684209e86a67b94641353f89500f1a943dced/src/extract.jl#L187-L199
If it's not the case, the solution of the linear system is the closest one in term of least square errors.
To check that it is indeed the same, you can compare `μ = measure(M)` and `measure(at, monomials(μ))`.
In this case, they are different hence you get different scalar product with `P` which explains the gap:
```julia
julia> using LinearAlgebra
julia> dot(measure(M), P)
44.93358174249377
julia> dot(at, P)
78.3392339877376
```
The atoms returned by `extractatoms` can always be used to get upper bounds but to ensure that you have found the optimal solution, they need to match.

**Comment by edljk** [comment]
Thank you, that makes sense for me.
Still, is it possible in another way to find one optimal vector `(x[i])`?

**Comment by edljk** [comment]
Closing this issue :it seems that the problem is more related to my specific problem (confirmed by  GloptiPoly).
Thanks again for your work / comments.
