### ISSUE TITLE
How to cite this software in a paper?

### ISSUE THREAD

**Issue by bachirelkhadir** [JuliaOpt/SumOfSquares.jl#157]
Hi,

Thank you guys for doing such a great work on this package!

What is the preferred way to cite this SumOfSquares.jl in an academic paper?

**Comment by blegat** [comment]
Thanks for referencing our work, we are glad to read that the package is useful to you.
The bibtex entry to cite is available [in the CITATION.bib file](https://github.com/JuliaOpt/SumOfSquares.jl/blob/master/CITATION.bib).
I added a more recent one in https://github.com/JuliaOpt/SumOfSquares.jl/pull/158 and links from the README to this CITATION.bib files.

**Comment by bachirelkhadir** [comment]
Wonderful. Thank you!
