### ISSUE TITLE
UndefVarError: MonomialVector not defined

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/SumOfSquares.jl#28]
I'm not sure where this used to be defined, but I'm getting precompilation errors now:
```
julia> using SumOfSquares
INFO: Precompiling module SumOfSquares.
ERROR: LoadError: LoadError: UndefVarError: MonomialVector not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
while loading /Users/huchette/.julia/v0.6/SumOfSquares/src/certificate.jl, in expression starting on line 24
while loading /Users/huchette/.julia/v0.6/SumOfSquares/src/SumOfSquares.jl, in expression starting on line 11
ERROR: Failed to precompile SumOfSquares to /Users/huchette/.julia/lib/v0.6/SumOfSquares.ji.
```
On julia v0.6.0, with
```
julia> Pkg.status()
...
 - MultivariatePolynomials       0.0.2+             master
 - PolyJuMP                      0.0.1+             master
 - SemialgebraicSets             0.0.0-             master (unregistered)
 - SumOfSquares                  0.0.1+             master
...
```

**Comment by blegat** [comment]
SumOfSquares needs to be updated for the new version of MultivariatePolynomials. I am trying to finish this today but currently the julia compiler is doing an infinite loop in precompilation :'(

**Comment by blegat** [comment]
Should have been fixed by #26

**Comment by joehuchette** [comment]
Any leads on the infinite loop in type inference? I'm also seeing it...

**Comment by blegat** [comment]
When I had the infinite loop, Istopped working on the SumOfSquares package for a few days since I also had to change stuff in SemialgebraicSets, MultivariateMoments, ... When I tried SumOfSquares again the infinite loop was gone and it never came back. Probably checking out the latest version of these packages could help.

**Comment by joehuchette** [comment]
Haha ok, I'll play around with it some more.

**Comment by blegat** [comment]
It should be fixed by the new version v0.1.0

**Comment by blegat** [comment]
@joehuchette do you confirm that this is fixed ?

**Comment by joehuchette** [comment]
Seems to be!
