### ISSUE TITLE
Release v0.1.1

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/SumOfSquares.jl#35]
I would like to enable Zenodo and release v0.1.1 since https://github.com/JuliaOpt/SumOfSquares.jl/pull/33 is an important fix.
@joehuchette @rdeits @chriscoey Any objection ?

**Comment by rdeits** [comment]
Sounds good to me

**Comment by joehuchette** [comment]
Go for it!

**Comment by blegat** [comment]
Done :)
