### ISSUE TITLE
Problems occur when extracting minimizer with AtomicMeasure

### ISSUE THREAD

**Issue by AlwaysPS** [JuliaOpt/SumOfSquares.jl#36]
I'm a newbie in Julia. When searching an easy-to-use SOS programming library I found SumOfSquares and decide it will be my choice.

I need to extract minimizer(i.e. the argument that minimizes objective function). I tried the way suggested in the slides of Benoît Legat. but I get a `UndefVarError: AtomicMeasure not defined` error. 

Assuming I need to include `AtomicMeasure` from somewhere else, I tried adding `Using MultivariateMoments` in the beginning. Then I get a
```
MethodError: Cannot convert an object of type MultivariateMoments.Measure{Float64,DynamicPolynomials.Monomial{true},DynamicPolynomials.MonomialVector{true}} to an object of type MultivariateMoments.AtomicMeasure
This may have arisen from a call to the constructor MultivariateMoments.AtomicMeasure(...),
since type constructors fall back to convert methods.
```

Is it because I include the wrong `AtomicMeasure` or something changed in `AtomicMeasure` and makes it unusable for extracting minimizer?

**Comment by blegat** [comment]
The function has been renamed to `extractatoms(::MatMeasure, ranktol)` (see https://github.com/JuliaAlgebra/MultivariateMoments.jl/blob/cd581f7922f83eb3278ea7d92909035d2056ca98/src/extract.jl#L146). The measure needs to be a `MatMeasure` and not a `Measure` (you can make the conversion using https://github.com/JuliaAlgebra/MultivariateMoments.jl/blob/master/src/matmeasure.jl#L62.
Let me know how it goes ! :)

**Comment by AlwaysPS** [comment]
Thank you for the quick reply!

I tried ```extractatoms(::MatMeasure, ranktol)``` and  ```matmeasure```. It seems ```matmeasure``` requires one more argument besides the ```Measure``` returned by ```getdual```, and ```extractatoms``` requires two more.

With little knowledge on both the Julia's templates(?) and moments theory, I've been unable to deduce what those arguments should be. By making some wild guess the additional argument in matmeasure should be a 3 elements array in my example(with 2 ```polyvar``` and one decision variable), but I have no idea what the other two arguments should be.

Here is the code, it's just a transcript of the example code in slides of Benoît Legat:

```
using MultivariatePolynomials
using MultivariateMoments
using JuMP
using PolyJuMP
using SumOfSquares
using DynamicPolynomials
using Mosek

@polyvar x y
p = x^3 - x^2 + 2x*y -y^2 + y^3
S = @set x >= 0 && y >= 0 && x + y >= 0

m = SOSModel(solver = MosekSolver())
@variable m lb
@objective m Max lb
constr = @constraint m p >= lb domain = S

status = solve(m)
extractatoms(matmeasure(getdual(constr), [1, x, y]))
```

**Comment by blegat** [comment]
For extracting the atoms from a MatMeasure, you need to first SVD or Cholesky decomposition and discard the part of the decomposition that is negligible. The purpose of `ranktol` is to determine what is the threshold. You can play with this value (try `1e-3`, `1e-4`, ...) to see what works best. The more the solver is accurate, the lower this value can be.
The third argument can either be `SVDChol()` (it is the default) or `ShiftChol(shiftvalue)` (e.g. `ShiftChol(1e-14)`). You can leave the default or try `ShiftChol`, or play with both and select the one which works best for you :) The first do an SVD and the second do Cholesky by first shifting all the eigenvalues. The reason of the shift is that Cholesky does not work if the matrix is not PSD and sometimes if the eigenvalue is 1e-16, because of numerical errors, cholesky fails. By shifting it by a 1e-14, it becomes 1e-14+1e-16 and that may work better :)

For the `matmeasure` argument, you can do `getmonomialsforcertificate(monomials(getdual(constr)))`

**Comment by AlwaysPS** [comment]
I tried using the default ```SVDChol``` and ```ShiftChol```, but every time I tried ```ShiftChol``` I get a ```Base.LinAlg.PosDefException```, so I had to stick with the default one.

The problem is, when used with a ```ranktol``` less than 1/3, I get no value from ```extractatom``` because it computed a non-zerodimensional support x + y == 1. However,  that set includes the true minimizer (1, 0) and (0, 1).

When ```ranktol``` is larger than 1/3, it returned (1/2, 1/2) "with weight -1", but the function takes value 1/4 at (1/2, 1/2), (significantly) larger than the optimal value 0 (and the Mosek solver get the value!).

Does numerical error cause this problem? Is there a way to get around it?

**Comment by blegat** [comment]
Isn't the minimizer (2/3, 0) with objective value -4/27 ?
By the way, in your set
```julia
S = @set x >= 0 && y >= 0 && x + y >= 0
```
the inequality `x + y >= 0` is redundant. Did you mean `x + y >= 1` ?

**Comment by AlwaysPS** [comment]
Yes, that actually is ```x + y >= 1```, I messed it up and forgot to change it back.

The case ```x+y >= 1```, however, is minimized by (1, 0) and (0, 1) with objective value 0.

**Comment by blegat** [comment]
> every time I tried ShiftChol I get a Base.LinAlg.PosDefException, so I had to stick with the default one

That's because the matrix is negative definite, you need to take `-1 * getdual(constr)`.

If you do not get atoms, you need to increase the degree of the polynomials used for the domain.
I have added a `maxdegree` keyword argument to do that and a notebook that should help you in https://github.com/JuliaOpt/SumOfSquares.jl/pull/38.
By the way, does your example comes from a book that I should cite or have you made it up ?

To use the `maxdegree` feature, you should do
```julia
julia> Pkg.update()
julia> Pkg.checkout("PolyJuMP", "bl/kwargs")
julia> Pkg.checkout("SumOfSquares", "bl/polyopt")
```
because these changes are not released yet. You can undo these changes with `Pkg.free("PolyJuMP")` and `Pkg.free("SumOfSquares")` later.

**Comment by AlwaysPS** [comment]
By using `-1 * getdual(constr)` and raise the shift to 1e-7 the exception disappears. That alone didn't fix the problem, though.

I tried `maxdegree` feature on my computer(In my computer I need to do `Pkg.checkout(*, "master")` before checkouting to another branch). Even when the maxdegree is set to 35 I still didn't get atoms. I think it may not be that degree used in the domain is lower than enough. Since Mosek did give the right optimal value without specify `maxdegree`, and indeed for this particular case we have:
```
x^3 - x^2 + 2xy -y^2 + y^3 = y^2 * x + x^2 * y + (x-y)^2 * (x+y-1)
```
so degree 3 will be enough.

The example is taken from the JuMP Meetup 2017 slides listed in `README.md`.

**Comment by blegat** [comment]
Which version of Mosek are you using ? I have Release 8.1.0.23.
In the notebook, I also have 0 for maxdegree 3 but that does not mean that atoms can be extracted. Having the right lower bound is a necessary condition for the presence of atoms but not a sufficient one.
What is your output for maxdegree 5 ?
I have
```julia
julia> μ5.a
21-element Array{Float64,1}:
 2.12919   
 0.380139  
 0.272624  
 0.272624  
 0.380139  
 2.1297    
 0.499951  
 4.67999e-5
 5.17568e-5
 4.67999e-5
 0.500462  
 0.499744  
 2.24694e-8
 2.24694e-8
 0.500256  
 0.499744  
 9.75507e-9
 0.500256  
 0.499744  
 0.500256  
 1.0
julia> getmat(ν5)
6×6 Array{Float64,2}:
 0.499951    4.67999e-5  5.17568e-5  0.499744    2.24694e-8  0.499744  
 4.67999e-5  5.17568e-5  4.67999e-5  2.24694e-8  2.24694e-8  9.75507e-9
 5.17568e-5  4.67999e-5  0.500462    2.24694e-8  0.500256    0.500256  
 0.499744    2.24694e-8  2.24694e-8  0.499744    9.75507e-9  0.499744  
 2.24694e-8  2.24694e-8  0.500256    9.75507e-9  0.500256    0.500256  
 0.499744    9.75507e-9  0.500256    0.499744    0.500256    1.0
```

> The example is taken from the JuMP Meetup 2017 slides

Ups, I didn't recognize it ^^

**Comment by AlwaysPS** [comment]
I'm using Release 8.1.0.53.

I think I found the reason. I use `[1 x y]` as the second argument of `matmeasure` even when I'm specifying `maxdegree`. By substituting it with `getmonomialsforcertificate(monomials(getdual(constr)))` I got the right `AtomicMeasure` when specifying `maxdegree` to be 5 and `ranktol` to be 1e-3

I also found one thing counter-intuitive: when `ranktol` is 1e-3 I got no atoms for `maxdegree` larger than 8. I need to lower `ranktol` to get the right atoms. That seems to be a natural result of floating error, but the silent changing of behaviour makes me nervous...

**Comment by blegat** [comment]
> That seems to be a natural result of floating error, but the silent changing of behaviour makes me nervous...

Then we should probably change the value `1e-3` to a lower one in the notebook.
The `ranktol` argument is definitely critical. That is why it has no default value, one should definitely pay attention to it and it is tricky to get the right value.
