### ISSUE TITLE
Unsatisfiable requirements detected for package Taro

### ISSUE THREAD

**Issue by Balance37** [JuliaOpt/SumOfSquares.jl#50]
I was trying to use "add Taro" to install Taro by using Julia 1.0, but an error occured.

(v1.0) pkg> add Taro
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Taro [61d0e4fa]:
 Taro [61d0e4fa] log:
 ├─possible versions are: [0.1.0-0.1.4, 0.2.0-0.2.1, 0.3.0-0.3.1, 0.4.0, 0.5.0, 0.6.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0-0.1.4, 0.2.0-0.2.1, 0.3.0-0.3.1, 0.4.0, 0.5.0, 0.6.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

**Comment by blegat** [comment]
This should probably be reported in [Taro's repo](https://github.com/aviks/Taro.jl), this does not seem related to this package, is it ?

**Comment by Balance37** [comment]
> This should probably be reported in [Taro's repo](https://github.com/aviks/Taro.jl), this does not seem related to this package, is it ?

Thanks!!
