### ISSUE TITLE
Leveraging the extensible design of MOI + JuMP v0.19

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/SumOfSquares.jl#66]
We should make use of the [extensible design of MOI + JuMP v0.19](http://www.juliaopt.org/JuMP.jl/dev/extensions/) to make PolyJuMP/SumOfSquares more deeply integrated into JuMP/MOI.
Now that JuMP v0.19 is in beta, it is a good time to implement these changes to make sure that no change is needed in JuMP v0.19 before it is released.

- [x] Replace `PolyJuMP.createpoly` by `JuMP.add_variable(::JuMP.AbstractModel, PolyJuMP.Variable)`
- [ ] Replace `addpolyconstraint!` by `JuMP.build_constraint` (requires https://github.com/JuliaOpt/JuMP.jl/pull/1707) : https://github.com/JuliaOpt/PolyJuMP.jl/pull/35
- [ ] Implement the SOS transformation using [MOI bridges](http://www.juliaopt.org/MathOptInterface.jl/stable/apimanual/#Constraint-bridges-1).
- [ ] Implement the WSOS transfoormation using MOI bridges.

cc @ccoffrin

**Comment by blegat** [comment]
Tests will be failing before we do that because JuMP now passes keyword arguments in `build_constraint`: https://github.com/JuliaOpt/JuMP.jl/pull/1707

**Comment by chriscoey** [comment]
Great! Let me know if you'd like to discuss.

@lkapelevich
