### ISSUE TITLE
Example is not working with MOSEK

### ISSUE THREAD

**Issue by IgnacioRubioScola** [JuliaOpt/SumOfSquares.jl#72]
The example: 
```julia
using DynamicPolynomials
using SumOfSquares
using MathOptInterfaceMosek
@polyvar x
P = [x^2 - 2x + 2 x
            x     x^2]
factory = with_optimizer(MosekOptimizer, QUIET=true);
@polyvar y[1:2]
p = vec(y)' * P * vec(y)
model = SOSModel(factory)
cref = @constraint(model, p in SOSCone())
JuMP.optimize!(model)
JuMP.termination_status(model)
```
gives:

> > ERROR: Mosek.MosekError(1385, "The A matrix element at constraint '' (22), variable '' (1) is specfied twice.")

and I'm using:
> > DynamicPolynomials v0.1.2
> > SumOfSquares v0.2.1+ #master (https://github.com/JuliaOpt/SumOfSquares.jl.git)
> > Mosek v0.9.8
> > MathOptInterfaceMosek v0.5.1
> > JuMP v0.18.5+ #master (https://github.com/JuliaOpt/JuMP.jl.git)
> > PolyJuMP v0.2.1+ #master (https://github.com/JuliaOpt/PolyJuMP.jl.git)
 

Thank you,

Ignacio Rubio Scola

**Comment by blegat** [comment]
You need the master version of MathOptInterfaceMosek to have this PR: https://github.com/JuliaOpt/MathOptInterfaceMosek.jl/pull/62

**Comment by blegat** [comment]
Should be resolved by https://github.com/JuliaLang/METADATA.jl/pull/21404#event-2137412268, please reopen if it's not the case
