### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/SumOfSquares.jl#77]
- [x] motzkin
- [x] goldsteinprice
- [x] Sum-of-Squares Matrices 4e58360dd70c93aa85c8b559125b33196901022c
- [ ] Polynomial Optimization

**Comment by barpit20** [comment]
@blegat You updated the Sum-of-Squares Matrices yesterday. In case you haven't started work on the last one, can I give it a go?

**Comment by blegat** [comment]
Yes please do, I am currently working on https://github.com/JuliaOpt/MosekTools.jl/issues/14
