### ISSUE TITLE
Domains not working properly with PSD constraints

### ISSUE THREAD

**Issue by lkapelevich** [JuliaOpt/SumOfSquares.jl#79]
For the following problem `py=y^3` should be a solution, but it is infeasible.
```julia
using SumOfSquares, DynamicPolynomials, SCS
model = SOSModel(with_optimizer(SCS.Optimizer))
@polyvar y[1:1]
@variable(model, py, Poly(monomials(y, 0:3)))
H = differentiate(py, y, 2)
@constraint(model, H in PSDCone(), domain = (@set y[1] >= 0))
@constraint(model, -H in PSDCone(), domain = (@set y[1] <= 0))
@constraint(model, py(2) == 8)
@constraint(model, py(-2) == -8)
@constraint(model, py(1) == 1)
@constraint(model, py(-1) == -1)
optimize!(model)
JuMP.termination_status(model) # INFEASIBLE::TerminationStatusCode = 2
```

**Comment by blegat** [comment]
Are you sure this is not because of the gap between SOS polynomials and nonnegative polynomials ?

**Comment by blegat** [comment]
For this example there should be no gap though

**Comment by lkapelevich** [comment]
Right the Hessian would be just degree 1

**Comment by blegat** [comment]
Looks like we drop the `kws` instead of passing it here:
https://github.com/JuliaOpt/SumOfSquares.jl/blob/ae1dc33f8da8bdd361004fcb07167b38dd148e99/src/constraint.jl#L86

**Comment by blegat** [comment]
Thanks for reporting this, silent bugs are the worst!

**Comment by lkapelevich** [comment]
Of course!
