### ISSUE TITLE
M[1:N,1:N] SDSOSPoly(vx) not working 

### ISSUE THREAD

**Issue by IgnacioRubioScola** [JuliaOpt/SumOfSquares.jl#87]
I cannot create a matrix of SDSOS's, SOS and DSOS are working well
Thank you,
Ignacio

```julia
using SumOfSquares
using DynamicPolynomials

@polyvar x1 x2
m = SOSModel()
@polyvar x[1:2];
vx = monomials(x,0:2);
@variable m SD1 SDSOSPoly(vx); #works fine
@variable m SOS[1:2,1:2] SOSPoly(vx); #works fine
@variable m DSOS[1:2,1:2] SOSPoly(vx); #works fine
@variable m SD2[1:2,1:2] SDSOSPoly(vx); #gives error
```
> ERROR: MethodError: no method matching GramMatrix{VariableRef,Monomial{true},MonomialVector{true}}(::GramMatrix{GenericAffExpr{Float64,VariableRef},Monomial{true},MonomialVector{true}})

**Comment by blegat** [comment]
Good catch, thanks for reporting this !
The situation should be improved once https://github.com/JuliaOpt/JuMP.jl/issues/525 is resolved but we can provide an easy fix in the meantime.
