### ISSUE TITLE
How can the Top homogeneous component be extracted?

### ISSUE THREAD

**Issue by IgnacioRubioScola** [JuliaOpt/SumOfSquares.jl#93]
Is there a way to extract the top homogeneous component of a SOSPoly?
The top homogeneous component of a polynomial _p_ is the homogeneous polynomial formed by the collection of the highest order monomials of _p_ [1].

Thank you,

Ignacio

[1] A.A. Ahmadi and P.A. Parrilo, "Sum of Squares Certificates for Stability of Planar, Homogeneous, and Switched Systems", 2017, IEE Transactions on Automatic Control, Vol 62, No 10, 5269--5274

**Comment by IgnacioRubioScola** [comment]
```
using JuMP
using SumOfSquares
using DynamicPolynomials
using LinearAlgebra

m = SOSModel(); 
@polyvar x[1:N];
mg=3;
vx = monomials(x,0:mg);
@variable m V SOSPoly(vx);
for i in V.x.Z
    if sum(i)==mg
       print(i)
       #Part of the Top homogeneous component
    end
end
```
I don't know how to recover the coefficient of V for that specific V.x.Z.

**Comment by blegat** [comment]
If you want to do it for a polynomial, you can do it like this:
```julia
julia> @polyvar x y
(x, y)

julia> p = x^2 + 2x*y + y + 2
x² + 2xy + y + 2
polyvar x y
(x, y)

julia> p = x^2 + 2x*y + y + 2
x² + 2xy + y + 2

polyvar x y
(x, y)

julia> p = x^2 + 2x*y + y + 2
x² + 2xy + y + 2

polyvar x y
(x, y)

julia> p = x^2 + 2x*y + y + 2
x² + 2xy + y + 2

julia> maxdegree(p)
2

julia> sum(term for term in terms(p) if degree(term) == 2)
x² + 2xy
```
You can transform `V` into a polynomial by doing `polynomial(V)`.

**Comment by IgnacioRubioScola** [comment]
yes, it's worked!
Thank you!

**Comment by blegat** [comment]
Glad it helped :)
