### ISSUE TITLE
Problems with coding "Strict" SOS

### ISSUE THREAD

**Issue by IgnacioRubioScola** [JuliaOpt/SumOfSquares.jl#94]
I am having problems to code "strict" SOS, a symmetric matrix M(x) with SOS polynomial as element is strict SOS in [x,y] if `y'(M(x)-eps*Id)y>0` with `eps>0` and `Id` is the identity matrix.
I managed to reproduce the numerical example from [1] using YALMIP and MOSEK, but I can't with SumOfSquares, hereafter what I tried to code.
Thank you,
Ignacio
[1] E.M. Aylwardm, P.A Parrilo, J.E. Slotine. Stability and Robustness analysis of nonlinear systems via contraction metrics and SOS metrics and SOS programming. Automatica, Vol.44, 2008.
```julia
# Example 4.1 Moore-Greitzer jet engine model [1]
using JuMP
using SumOfSquares
using DynamicPolynomials
using LinearAlgebra
using MosekTools
m = SOSModel(with_optimizer(Mosek.Optimizer, QUIET=false)); 
PolyJuMP.setdefault!(m, PolyJuMP.NonNegPoly, SOSCone)
# ==================
nmm=0; #minimum monomials degree 
nMm=2; #maximum monomials degree 
# ==================
N=2; #Order of the system
@polyvar x[1:N]; # x variable
# ==================
f=[-x[2]-3/2*x[1]^2-1/2*x[1]^3; 3*x[1]-x[2]]; # System
J=differentiate(f,x)'; # Jacobian of the system
# ==================
vx = monomials(x,nmm:nMm); #Molynomials for M(x)[:,:]
# ==================
nsys=trunc(Int,(N+1)*N/2); #Number of elements of the Symmetric M matrix
@variable m vM[1:nsys] SOSPoly(vx);
# ==================
# Preallocation
M=Array{Polynomial{true,GenericAffExpr{Float64,VariableRef}}}(undef, N,N);
dM=Array{Polynomial{true,GenericAffExpr{Float64,VariableRef}}}(undef, N,N);
# ==================
global k=0;
for i=1:N
    for j=i:N
        global k+=1;
        M[i,j]=vM[k]; #Creating M(x) as a symmetric matrix with SOS elements
        dM[i,j]=differentiate(M[i,j], x)'*f; #Computing \dot{M}(x)
        if i!=j #Symmetric parts 
            M[j,i]=M[i,j]; #of M(x) 
            dM[j,i]=dM[i,j]; #and \dot{M}(x)
        end
    end
end
lam=0.7; #Maximum contraction rate, should be at least around 0.78 (or 0.99) for 4 (or 6) M degree polynomial 
R=dM+J'*M+M*J+lam*M; #Contraction condition 
# ==================
# ==================
Id=Matrix{Float64}(I, N, N); # Identity matrix
eps1=1e-5; #Epsilon to achieve strict SOS condition
# ==================
@polyvar y[1:N]; #Free variable to have a scalar SOS condition
@constraint m y'*(M-Id*eps1)*y >=0; #M must be Strict SOS
@constraint m y'*(-R-Id*eps1)*y >=0; #R must be Strict SOS
# ==================
JuMP.optimize!(m);
@show JuMP.termination_status(m);
@show maxdegree(M[1,1]);
```

**Comment by blegat** [comment]
What is the issue with the code ?
Note that you can do
```julia
@constraint(m, M-Id*eps1 in PSDCone())
@constraint(m, -R-Id*eps1 in PSDCone())
```
which generates a smaller SDP, see [the Sum-of-Squares Matrices notebook](https://github.com/JuliaOpt/SumOfSquares.jl/blob/master/examples/Sum-of-Squares%20Matrices.ipynb) for details.

**Comment by IgnacioRubioScola** [comment]
The problem is that its gives infeasible except if `eps1=0` which is incorrect, with an `eps1` small (but greater than the solver tolerance) should be feasible.
When I try 
```
@constraint (m, (M-Id*eps1) in SOScone());
@constraint (m, (-R-Id*eps1) in SOScone()); 
```
gives error
> ERROR: LoadError: In `@constraint((m, M - Id * eps1 in SOScone()))`: Not enough arguments
the same error appears with `PSDcone`

**Comment by blegat** [comment]
There should be no space between `@constraint` and `(`

**Comment by IgnacioRubioScola** [comment]
Ohh ok, thank you, now its gives same problem using PSDCone.
I think that I know my issue: I want to find a feasible solution to a SOSPoly that is in the SOSCone and but I don't want the trivial one.
I was doing `P-eps>0` but it gives feasible only if `P` has the term `x^0 `so I replace by  `P-P.x'*P.xeps>0`
```
using JuMP
using SumOfSquares
using DynamicPolynomials
using MosekTools
m = SOSModel(with_optimizer(Mosek.Optimizer, QUIET=true)); 
PolyJuMP.setdefault!(m, PolyJuMP.NonNegPoly, SOSCone)
@polyvar x;
vx = monomials(x,2:4);
@variable m P SOSPoly(vx);
@constraint m P-1e-5*P.x'*P.x >=0; # works fine
# @constraint(m, P-1e-5*P.x'*P.x in PSDCone()); #gives error :(
JuMP.optimize!(m);
@show JuMP.termination_status(m);
```
I think `eps*P.x'*P.x` solves my problem to avoid the trivial solution (May be there is better way?).
I don't understand why `@constraint(m, P-1e-5*P.x'*P.x in PSDCone())` gives error:
> ERROR: LoadError: MethodError: no method matching build_constraint(::getfield(JuMP, Symbol("#_error#55")){Symbol}, ::Polynomial{true,GenericAffExpr{Float64,VariableRef}}, ::PSDCone)

**Comment by blegat** [comment]
For PSDCone, you need to have a matrix of polynomial, here `P-1e-5*P.x'*P.x` is only a polynomial, not a matrix

**Comment by blegat** [comment]
Closing as stale
