### ISSUE TITLE
moments and duals

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/SumOfSquares.jl#98]
For a constraint, `dual` is currently only implemented where there is no domain, see
https://github.com/JuliaOpt/SumOfSquares.jl/blob/b24d88e7e5dc2d848a7ee974b15697f421ee814e/src/sos_polynomial_in_semialgebraic_set_bridge.jl#L110-L114
Consider for instance:
```julia
csos = @constraint(p(x) in SOSCone(), domain = @set q_1(x) >= 0 && q_2(x) >= 0)
```
Internally, we create gram matrices, `s_0(x)`, `s_1(x)` and `s_2(x)` and add a constraint equivalent to
```julia
ceq = @constraint(p(x) == s_0(x) + s_1(x) * q_1(x) + s_2(x) * q_2(x))
```
From the solver we can get two dual information
1) The dual of the constraint that `s_0(x)` is SOS, this can be obtained by `moment_matrix`
2) The dual of the equality `ceq` which is a list of moments for the monomials in `p(x)` or `s_0(x)` or `s_1(x) * q_1(x)` or `s_2(x) * q_2(x)`. Note that there may be more monomials than the monomials in `p(x)`.

In MOI, the constraint `csos` is passed as `coefficients(p) in ...` and the dual is reconstructed from the dual of the MOI constraint (which is therefore a vector of number of the same length as the number of coefficients in `p`) and the shape of the constraint (which contains `monomials(p)`). Therefore, the dual of `csos` has to be the moments for the monomials of `p(x)` and hence cannot always contain all the moments in the dual of `ceq`.

We discussed about this with @tweisser and suggest the following:
* `moments(csos)` gives `dual(ceq)` (which is equivalent to `moments(ceq)`).
* `dual(csos)` gives the moments of `moments(csos)` corresponding to the monomials of `p`.

What do you think ?

**Comment by blegat** [comment]
For constraint in algebraic sets, things are a bit more complicated. Let's see it with an example.
Consider the constraint
```julia
@polyvar x
@variable(model, a)
@variable(model, b)
@constraint(model, a * x + b in SOSCone(), domain = @set x == 1)
```
When taking the remainder in
https://github.com/JuliaOpt/PolyJuMP.jl/blob/3eb801269da0b43ca637dffe3ab361680c97d824/src/zero_polynomial_in_algebraic_set_bridge.jl#L13
the polynomial `a * x + b` is transformed into `a + b`.
So the constraint `[a, b] in SOS(...)` is transformed into `[a + b] in MOI.Zeros(1)`.
That is, given the matrix `A = [1 1]`, the vector is multiplied by `A`.
This means that the dual of the transformed constraint should be multiplied by `A*`.
So if the transformed constraint give the dual `[d]`, the dual of the original constraint will be `[d, d]` so the moment of `x` is `d` and the moment of `1` is `d`.
In practice what we can do is take each element of the base (works with any base, not only the monomial basis), take its remainder modulo the ideal and then take the scalar product between the resulting polynomial and the dual of the transformed constraint (which is a moment serie).

**Comment by chriscoey** [comment]
just to check if I understand correctly what we're discussing here:
suppose for simplicity that there are no equality constraints in the domain. then we have a single WSOS constraint that looks like b + Ax in WSOS(domain). we want to obtain the dual on that constraint from the duals on the PSD constraints in the extended formulation. so it's like reconstructing the original dual through the WSOS -> PSDs bridge?

**Comment by blegat** [comment]
> so it's like reconstructing the original dual through the WSOS -> PSDs bridge?

Not sure to understand what you mean, getting the dual from the bridge is what we want but it's quite general and you might mean something specific
